data = [
    {"name": "Virat Kohli", "profession": "Cricketer", "age": 36, "number_of_followers_on_instagram": 286},
    {"name": "Priyanka Chopra", "profession": "Actor, Singer", "age": 43, "number_of_followers_on_instagram": 94},
    {"name": "Shraddha Kapoor", "profession": "Actor", "age": 38, "number_of_followers_on_instagram": 94},
    {"name": "Alia Bhatt", "profession": "Actor", "age": 32, "number_of_followers_on_instagram": 91},
    {"name": "MS Dhoni", "profession": "Cricketer", "age": 44, "number_of_followers_on_instagram": 47},
    {"name": "Deepika Padukone", "profession": "Actor", "age": 39, "number_of_followers_on_instagram": 79},
    {"name": "Ranveer Singh", "profession": "Actor", "age": 40, "number_of_followers_on_instagram": 47},
    {"name": "Katrina Kaif", "profession": "Actor", "age": 42, "number_of_followers_on_instagram": 83},
    {"name": "Sachin Tendulkar", "profession": "Cricketer", "age": 52, "number_of_followers_on_instagram": 50},
    {"name": "Kiara Advani", "profession": "Actor", "age": 33, "number_of_followers_on_instagram": 51},
    {"name": "Anushka Sharma", "profession": "Actor", "age": 37, "number_of_followers_on_instagram": 68},
    {"name": "Akshay Kumar", "profession": "Actor", "age": 57, "number_of_followers_on_instagram": 70},
    {"name": "Hrithik Roshan", "profession": "Actor", "age": 51, "number_of_followers_on_instagram": 49},
    {"name": "Salman Khan", "profession": "Actor", "age": 59, "number_of_followers_on_instagram": 72},
    {"name": "Amitabh Bachchan", "profession": "Actor", "age": 82, "number_of_followers_on_instagram": 37},
    {"name": "Kriti Sanon", "profession": "Actor", "age": 35, "number_of_followers_on_instagram": 55},
    {"name": "Janhvi Kapoor", "profession": "Actor", "age": 28, "number_of_followers_on_instagram": 25},
    {"name": "Sara Ali Khan", "profession": "Actor", "age": 30, "number_of_followers_on_instagram": 46},
    {"name": "Neha Kakkar", "profession": "Singer", "age": 37, "number_of_followers_on_instagram": 78},
    {"name": "Shahid Kapoor", "profession": "Actor", "age": 44, "number_of_followers_on_instagram": 48},
    {"name": "Karan Johar", "profession": "Director, Producer", "age": 53, "number_of_followers_on_instagram": 23},
    {"name": "Tiger Shroff", "profession": "Actor", "age": 35, "number_of_followers_on_instagram": 43},
    {"name": "Jacqueline Fernandez", "profession": "Actor", "age": 40, "number_of_followers_on_instagram": 67},
    {"name": "Arjun Kapoor", "profession": "Actor", "age": 40, "number_of_followers_on_instagram": 19},
    {"name": "Disha Patani", "profession": "Actor", "age": 33, "number_of_followers_on_instagram": 61},
    {"name": "Rashmika Mandanna", "profession": "Actor", "age": 29, "number_of_followers_on_instagram": 45},
    {"name": "Allu Arjun", "profession": "Actor", "age": 43, "number_of_followers_on_instagram": 29},
    {"name": "Kajal Aggarwal", "profession": "Actor", "age": 40, "number_of_followers_on_instagram": 25},
    {"name": "Kapil Sharma", "profession": "Comedian", "age": 44, "number_of_followers_on_instagram": 47},
    {"name": "Yami Gautam", "profession": "Actor", "age": 36, "number_of_followers_on_instagram": 18}
]
